// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using stackoverflowapi;

namespace stackoverflowapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190926204708_AddedTitle")]
    partial class AddedTitle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("stackOverFlowApi.Models.Answers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<int>("AnswerDislike");

                    b.Property<int>("AnswerLike");

                    b.Property<int?>("QuestionsId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionsId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("stackOverFlowApi.Models.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("QuestionContent");

                    b.Property<int>("QuestionDislike");

                    b.Property<int>("QuestionLike");

                    b.Property<string>("QuestionTitle");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("stackOverFlowApi.Models.Answers", b =>
                {
                    b.HasOne("stackOverFlowApi.Models.Questions", "Questions")
                        .WithMany("Answer")
                        .HasForeignKey("QuestionsId");
                });
#pragma warning restore 612, 618
        }
    }
}
